version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network
      #volumes:
      #  - zookeeper-data:/var/lib/zookeeper/data
      #  - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    #depends_on:
    #  zookeeper:
    #    condition: service_healthy
    ports:
      - "9092:9092"
      - "9093:9093"  # 用于外部访问（可选）
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"  # 调整堆内存大小
    networks:
      - kafka-network
      #volumes:
      #  - kafka-data:/var/lib/kafka/data
      #healthcheck:
      #  test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      #  interval: 10s
      #  timeout: 5s
      #  retries: 5

networks:
  kafka-network:
    driver: bridge

    # volumes:
    #   zookeeper-data: {"/home/cai/Code/Data/zookeeper/data/"}
    #   zookeeper-log: {"/home/cai/Code/Data/zookeeper/log/"}
    #   # kafka-data: {"/home/cai/Code/Data/kafka/data/"}